### ISSUE TITLE
TimeSeries "values" structured incorrectly

### ISSUE THREAD

**Issue by jbkolze** [HydrologicEngineeringCenter/cwms-data-api-client-javascript#3]
https://github.com/HydrologicEngineeringCenter/cwms-data-api-client-javascript/blob/4e1c0c8066986fb55882bdddb1fd978b6021c836/cwms-swagger.json#L9308-L9334

The "values" key in the TimeSeries return object is defined in the OpenAPI as an array of arrays of objects.  The actual returned object is just an array of arrays of numbers (with no actual definition/structure).  This is causing typing issues when using the cwmsjs library with TypeScript.

**Comment by MikeNeilson** [comment]
I'm going to copy this to the CDA repo. this library can't fix the issue. See https://github.com/USACE/cwms-data-api/issues/905

**Comment by jbkolze** [comment]
@MikeNeilson Thanks Mike.  Just FYI -- I think @krowvin might have made a couple other tweaks to the cwms-swagger.json in cwmsjs specifically (related to TimeSeriesGroups, possibly?  can't remember off of the top of my head) that it might make sense to touch base on as well.  Obviously the ideal situation is for the schema to work 1:1 for both -- not sure if there was some kind of conflict requiring changes to cwmsjs rather than the CDA base.

**Comment by MikeNeilson** [comment]
We discussed it a bit yesterday. My opinion is that, except for the things that actually require certain run time config elements (server, some of the security schemes) if automation can't pick up the openapi definition cleanly it's a bug unless specifically documented as to why we have that discrepency. For this one I suspect RMA just worked around it or went with it as it's not uncommon for us to map a tuple to an object like this. But it should be consistenly one or the other.

Further discssions of the "right" definition though should be put on the linked CDA issue.

**Comment by krowvin** [comment]
Just for reference 

> I think @krowvin might have made a couple other tweaks to the cwms-swagger.json

Here are those tweaks - in an issue

https://github.com/USACE/cwms-data-api/issues/818
